-- STANCE and STANCE_CHECK as pipeline node kinds.

ALTER TABLE pipeline_nodes DROP CONSTRAINT IF EXISTS pipeline_nodes_kind_check;
ALTER TABLE pipeline_nodes
  ADD CONSTRAINT pipeline_nodes_kind_check
    CHECK (kind IN (
      'TRIGGER','FILTER','RESOLVE_CONTEXT','MEDIA_RESOLVE','RELATIONSHIP','STANCE',
      'RETRIEVE_MEMORY','ASSEMBLE_PERSONA','GENERATE','VALIDATE','STANCE_CHECK',
      'CONDITION','APPROVAL_GATE','DELAY','EXECUTE_ACTION','MEMORY_WRITE','PERSIST','END'
    ));
