-- VOICE and QUALITY_GATE node kinds.

ALTER TABLE pipeline_nodes DROP CONSTRAINT IF EXISTS pipeline_nodes_kind_check;
ALTER TABLE pipeline_nodes
  ADD CONSTRAINT pipeline_nodes_kind_check
    CHECK (kind IN (
      'TRIGGER','FILTER','RESOLVE_CONTEXT','MEDIA_RESOLVE','RELATIONSHIP','STANCE',
      'ENGAGEMENT_DECISION','INTENT','RETRIEVE_MEMORY','ASSEMBLE_PERSONA','GENERATE',
      'VALIDATE','VOICE','QUALITY_GATE','STANCE_CHECK','CONDITION','APPROVAL_GATE',
      'DELAY','EXECUTE_ACTION','MEMORY_WRITE','PERSIST','END'
    ));
