/**
 * An agent's own wallet: keys, reads, and the only path by which value moves.
 *
 * ## What this module is, and what it is not
 *
 * It holds the rules and none of the chain code. Generating a key, turning it
 * into an address, reading a node, simulating, signing and broadcasting are
 * done by a `WalletAdapter`, which a first-party wallet Plugin supplies. The
 * rules are here so that they are the same whichever adapter is installed, and
 * so that no adapter can relax them:
 *
 * - A secret is generated by the adapter, sealed under the master key at once,
 *   and opened again only inside `submitIntent`, for the owner's approved
 *   transaction. It is never returned, logged, audited, traced or put in a
 *   browser task.
 * - Nothing a model can reach writes. The wallet capabilities read; intents are
 *   owner routes only.
 * - A transaction is two typed kinds, never calldata, never an approval, never
 *   a message to sign.
 * - Every intent is simulated, and the owner approves the digest of exactly
 *   what would be signed: nonce, fee caps, recipient, amount. An approval is
 *   for one transaction, expires, and cannot be reused.
 * - Submission is single-flight and never retried. The hash is written before
 *   the network sees the transaction; anything that goes wrong after that is
 *   UNKNOWN, and UNKNOWN is resolved by reading the chain for that hash.
 *
 * ## Loading the adapter
 *
 * The owner names a module file and its SHA-256 in the environment
 * (`AI17Z_WALLET_ADAPTER` and `AI17Z_WALLET_ADAPTER_SHA256`). The file is hashed
 * before it is imported and refused on any mismatch. This is not the Plugin
 * marketplace, where a Plugin declares and never ships code; it is a
 * first-party module the owner installed on their own machine and pinned.
 */
import { createHash, randomUUID } from 'node:crypto';
import { readFile } from 'node:fs/promises';
import { pathToFileURL } from 'node:url';
import { agents as agentsRepo, ops, wallets as walletsRepo, type WalletIntentRow, type WalletRow } from '@xbam/database';
import { NotFoundError, ValidationError, createLogger, errorMessage, openSecret, sealSecret } from '@xbam/shared';
import {
  APPROVAL_TTL_MS,
  WALLET_NETWORKS,
  WalletIntentParams,
  WalletSimulation,
  addressShapeOk,
  type WalletFamily,
  type WalletNetwork,
} from '@xbam/shared/contracts';

const log = createLogger('wallet');

// ── The adapter contract ────────────────────────────────────────────────────

export interface WalletBalance {
  symbol: string;
  /** Base units, as a string. */
  amount: string;
  decimals: number;
  /** A token's contract or mint; null for the native unit. */
  token: string | null;
}

export interface WalletActivity {
  txHash: string;
  direction: 'IN' | 'OUT' | 'SELF' | 'UNKNOWN';
  amount: string | null;
  symbol: string | null;
  at: string | null;
  status: 'CONFIRMED' | 'FAILED' | 'PENDING' | 'UNKNOWN';
}

export interface NetworkStatus {
  reachable: boolean;
  /** Latest block or slot, as a string. */
  height: string | null;
  /** The chain the node proved it serves, when it could be asked. */
  chainProof: string | null;
  detail: string;
}

/** What a first-party wallet adapter supplies. Every method may throw a sentence. */
export interface WalletAdapter {
  id: string;
  version: string;
  families: readonly WalletFamily[];
  generateSecret(family: WalletFamily): Uint8Array;
  addressOf(family: WalletFamily, secret: Uint8Array): string;
  /** Whether an address is valid for the family, checksum included. */
  validAddress(family: WalletFamily, address: string): boolean;
  balances(network: WalletNetwork, address: string): Promise<WalletBalance[]>;
  networkStatus(network: WalletNetwork): Promise<NetworkStatus>;
  recentActivity(network: WalletNetwork, address: string, limit: number): Promise<WalletActivity[]>;
  simulate(network: WalletNetwork, from: string, intent: WalletIntentParams): Promise<WalletSimulation>;
  /** Builds and signs exactly what the simulation pinned. Returns the hash and the bytes, and sends nothing. */
  sign(network: WalletNetwork, secret: Uint8Array, intent: WalletIntentParams, simulation: WalletSimulation): Promise<{ txHash: string; raw: string }>;
  broadcast(network: WalletNetwork, raw: string): Promise<void>;
  /** What the chain says about a hash now. */
  receipt(network: WalletNetwork, txHash: string): Promise<'CONFIRMED' | 'FAILED' | 'PENDING' | 'NOT_FOUND'>;
}

let adapter: WalletAdapter | null = null;
let loadError: string | null = null;

export function registerWalletAdapter(next: WalletAdapter): void {
  adapter = next;
  loadError = null;
}

export function resetWalletAdapterForTest(): void {
  adapter = null;
  loadError = null;
}

export function walletAdapter(): WalletAdapter | null {
  return adapter;
}

/** Why there is no adapter, as a sentence for the owner. */
export function walletReadiness(): { ready: boolean; detail: string } {
  if (adapter) return { ready: true, detail: `Wallet adapter ${adapter.id} ${adapter.version} is installed.` };
  return { ready: false, detail: loadError ?? 'No wallet adapter is installed, so wallets cannot be created or read.' };
}

function isAdapter(value: unknown): value is WalletAdapter {
  const a = value as Partial<WalletAdapter> | null;
  return Boolean(
    a &&
      typeof a.id === 'string' &&
      Array.isArray(a.families) &&
      ['generateSecret', 'addressOf', 'validAddress', 'balances', 'networkStatus', 'recentActivity', 'simulate', 'sign', 'broadcast', 'receipt'].every(
        (m) => typeof (a as Record<string, unknown>)[m] === 'function',
      ),
  );
}

/**
 * Loads the owner's wallet adapter, if they named one. Never throws: a wallet
 * that cannot load is a wallet that says so, and nothing else stops.
 */
export async function loadWalletAdapter(env: NodeJS.ProcessEnv = process.env): Promise<void> {
  const path = env.AI17Z_WALLET_ADAPTER?.trim();
  const pinned = env.AI17Z_WALLET_ADAPTER_SHA256?.trim().toLowerCase();
  if (!path) return;
  try {
    if (!pinned || !/^[0-9a-f]{64}$/.test(pinned)) {
      throw new Error('AI17Z_WALLET_ADAPTER is set without AI17Z_WALLET_ADAPTER_SHA256, so it was not loaded. Pin the file you installed.');
    }
    const bytes = await readFile(path);
    const actual = createHash('sha256').update(bytes).digest('hex');
    if (actual !== pinned) throw new Error('The wallet adapter file does not match its pinned SHA-256, so it was not loaded.');
    const module = (await import(pathToFileURL(path).href)) as { default?: unknown; walletAdapter?: unknown };
    const candidate = module.walletAdapter ?? module.default;
    if (!isAdapter(candidate)) throw new Error('The wallet adapter file does not export a wallet adapter.');
    registerWalletAdapter(candidate);
    log.info('wallet adapter loaded', { id: candidate.id, version: candidate.version });
  } catch (error) {
    loadError = errorMessage(error);
    log.warn('wallet adapter not loaded', { message: loadError });
  }
}

function requireAdapter(): WalletAdapter {
  if (!adapter) throw new ValidationError(walletReadiness().detail);
  return adapter;
}

async function requireOwned(agentId: string, ownerId: string): Promise<void> {
  const agent = await agentsRepo.getAgent(agentId);
  if (!agent || agent.ownerId !== ownerId) throw new NotFoundError('Agent');
}

function secretToText(secret: Uint8Array): string {
  return Buffer.from(secret).toString('base64');
}

// ── Wallets ─────────────────────────────────────────────────────────────────

/** Makes an agent's wallet for one family. The secret is sealed before this returns, and never leaves. */
export async function createWallet(input: { agentId: string; ownerId: string; family: WalletFamily }): Promise<WalletRow> {
  await requireOwned(input.agentId, input.ownerId);
  const a = requireAdapter();
  if (!a.families.includes(input.family)) throw new ValidationError(`The installed wallet adapter does not support ${input.family} wallets.`);
  const existing = (await walletsRepo.liveWallets(input.agentId)).find((w) => w.family === input.family);
  if (existing) return existing;
  const secret = a.generateSecret(input.family);
  try {
    const address = a.addressOf(input.family, secret);
    if (!a.validAddress(input.family, address)) throw new Error('The adapter produced an address it does not itself accept.');
    const wallet = await walletsRepo.createWallet({ agentId: input.agentId, family: input.family, address, sealedSecret: sealSecret(secretToText(secret)), adapter: a.id });
    await ops.audit({ actorUserId: input.ownerId, action: 'wallet.created', entityType: 'agent', entityId: input.agentId, data: { walletId: wallet.id, family: wallet.family, address: wallet.address } });
    return wallet;
  } finally {
    secret.fill(0);
  }
}

/** The owner says they hold a backup of the master key and the database. Recorded, never checked by guessing. */
export async function confirmWalletBackup(walletId: string, ownerId: string): Promise<WalletRow> {
  const wallet = await walletsRepo.getWallet(walletId);
  if (!wallet) throw new NotFoundError('Wallet');
  await requireOwned(wallet.agentId, ownerId);
  await walletsRepo.markBackedUp(walletId);
  await ops.audit({ actorUserId: ownerId, action: 'wallet.backup_confirmed', entityType: 'agent', entityId: wallet.agentId, data: { walletId } });
  return (await walletsRepo.getWallet(walletId))!;
}

export async function walletsOf(agentId: string, ownerId: string | null): Promise<WalletRow[]> {
  if (ownerId) await requireOwned(agentId, ownerId);
  return walletsRepo.liveWallets(agentId);
}

async function walletFor(agentId: string, network: WalletNetwork): Promise<WalletRow | null> {
  const family = WALLET_NETWORKS[network].family;
  return (await walletsRepo.liveWallets(agentId)).find((w) => w.family === family) ?? null;
}

// ── Reads, for the capabilities and the owner's screen ─────────────────────

export async function readBalances(agentId: string, network: WalletNetwork): Promise<{ address: string | null; balances: WalletBalance[]; detail: string }> {
  const wallet = await walletFor(agentId, network);
  if (!wallet) return { address: null, balances: [], detail: `There is no ${WALLET_NETWORKS[network].family} wallet for this agent.` };
  const balances = await requireAdapter().balances(network, wallet.address);
  return { address: wallet.address, balances, detail: `Read from ${WALLET_NETWORKS[network].label} just now.` };
}

export async function readActivity(agentId: string, network: WalletNetwork, limit: number): Promise<{ address: string | null; activity: WalletActivity[] }> {
  const wallet = await walletFor(agentId, network);
  if (!wallet) return { address: null, activity: [] };
  return { address: wallet.address, activity: await requireAdapter().recentActivity(network, wallet.address, limit) };
}

// ── Intents: the only way value moves ──────────────────────────────────────

/** The digest of exactly what would be signed. The owner approves this, and only this. */
export function intentDigest(input: { walletAddress: string; params: WalletIntentParams; simulation: WalletSimulation }): string {
  const canonical = JSON.stringify({
    from: input.walletAddress,
    network: input.params.network,
    chain: WALLET_NETWORKS[input.params.network].caip2,
    params: Object.fromEntries(Object.entries(input.params).sort(([a], [b]) => a.localeCompare(b))),
    maxFee: input.simulation.maxFee,
    pinned: Object.fromEntries(Object.entries(input.simulation.pinned).sort(([a], [b]) => a.localeCompare(b))),
  });
  return createHash('sha256').update(canonical).digest('hex');
}

async function ownedIntent(id: string, ownerId: string): Promise<{ intent: WalletIntentRow; wallet: WalletRow }> {
  const intent = await walletsRepo.getIntent(id);
  if (!intent) throw new NotFoundError('Transaction');
  await requireOwned(intent.agentId, ownerId);
  const wallet = await walletsRepo.getWallet(intent.walletId);
  if (!wallet) throw new NotFoundError('Wallet');
  return { intent, wallet };
}

async function intentAudit(ownerId: string, intent: WalletIntentRow, action: string): Promise<void> {
  await ops.audit({
    actorUserId: ownerId,
    action,
    entityType: 'agent',
    entityId: intent.agentId,
    data: { intentId: intent.id, network: intent.network, kind: intent.kind, status: intent.status, txHash: intent.txHash },
  });
}

/** An owner writes down a transaction. Nothing is simulated, signed or sent. */
export async function draftIntent(input: { agentId: string; ownerId: string; params: unknown; idempotencyKey?: string }): Promise<{ intent: WalletIntentRow; created: boolean }> {
  await requireOwned(input.agentId, input.ownerId);
  const parsed = WalletIntentParams.safeParse(input.params);
  if (!parsed.success) throw new ValidationError(`That is not a transaction AI17Z can make: ${parsed.error.issues.map((i) => i.message).join(' ')}`);
  const params = parsed.data;
  const network = WALLET_NETWORKS[params.network];
  const wallet = await walletFor(input.agentId, params.network);
  if (!wallet) throw new ValidationError(`This agent has no ${network.family} wallet to send from.`);
  const a = requireAdapter();
  if (!addressShapeOk(network.family, params.to) || !a.validAddress(network.family, params.to)) {
    throw new ValidationError(`${params.to} is not a valid ${network.label} address.`);
  }
  if (params.to === wallet.address) throw new ValidationError('That sends to the same wallet it comes from.');
  if (params.kind === 'TOKEN_TRANSFER' && !a.validAddress(network.family, params.token)) throw new ValidationError('The token address is not valid on that network.');
  const out = await walletsRepo.createIntent({
    walletId: wallet.id,
    agentId: input.agentId,
    ownerId: input.ownerId,
    network: params.network,
    kind: params.kind,
    params: params as unknown as Record<string, unknown>,
    idempotencyKey: input.idempotencyKey?.trim() || randomUUID(),
  });
  if (out.created) await intentAudit(input.ownerId, out.intent, 'wallet.intent.drafted');
  return out;
}

/** Asks the chain what would happen. Always the step before an approval, and repeatable until one. */
export async function simulateIntent(id: string, ownerId: string): Promise<WalletIntentRow> {
  const { intent, wallet } = await ownedIntent(id, ownerId);
  if (!['DRAFTED', 'AWAITING_APPROVAL', 'EXPIRED'].includes(intent.status)) throw new ValidationError('That transaction is past being simulated.');
  const params = WalletIntentParams.parse(intent.params);
  const simulation = WalletSimulation.parse(await requireAdapter().simulate(params.network, wallet.address, params));
  const digest = simulation.ok ? intentDigest({ walletAddress: wallet.address, params, simulation }) : null;
  const next = await walletsRepo.transitionIntent(id, ['DRAFTED', 'AWAITING_APPROVAL', 'EXPIRED'], simulation.ok ? 'AWAITING_APPROVAL' : 'DRAFTED', {
    simulation,
    digest,
    error: simulation.ok ? null : simulation.failure ?? 'It would fail.',
  });
  if (!next) throw new ValidationError('That transaction changed while it was being simulated. Look again.');
  return next;
}

/**
 * The owner approves exactly this transaction, by the digest they were shown.
 *
 * A digest that does not match means they were looking at something else,
 * perhaps an older simulation, and nothing is approved.
 */
export async function approveIntent(id: string, ownerId: string, digest: string): Promise<WalletIntentRow> {
  const { intent } = await ownedIntent(id, ownerId);
  if (intent.status !== 'AWAITING_APPROVAL' || !intent.digest) throw new ValidationError('That transaction is not waiting for approval. Simulate it first.');
  if (digest.trim().toLowerCase() !== intent.digest) throw new ValidationError('That is not the transaction currently simulated. Look at it again before approving.');
  const next = await walletsRepo.transitionIntent(id, 'AWAITING_APPROVAL', 'APPROVED', { approvedDigest: intent.digest, approvedBy: ownerId });
  if (!next) throw new ValidationError('That transaction was already decided.');
  await intentAudit(ownerId, next, 'wallet.intent.approved');
  return next;
}

export async function rejectIntent(id: string, ownerId: string): Promise<WalletIntentRow> {
  await ownedIntent(id, ownerId);
  const next = await walletsRepo.transitionIntent(id, ['DRAFTED', 'AWAITING_APPROVAL', 'APPROVED', 'EXPIRED'], 'REJECTED');
  if (!next) throw new ValidationError('That transaction can no longer be rejected.');
  await intentAudit(ownerId, next, 'wallet.intent.rejected');
  return next;
}

/**
 * Signs and sends one approved transaction, once.
 *
 * APPROVED -> SUBMITTING is the claim, so two presses cannot both sign. The
 * hash is written before the network sees anything. From SUBMITTING the only
 * ways out are SUBMITTED and UNKNOWN; there is no path back to APPROVED, so
 * there is no retry, blind or otherwise.
 */
export async function submitIntent(id: string, ownerId: string, now = Date.now()): Promise<WalletIntentRow> {
  const { intent, wallet } = await ownedIntent(id, ownerId);
  if (intent.status !== 'APPROVED' || !intent.approvedDigest || !intent.simulation) throw new ValidationError('Only an approved transaction can be sent.');
  const params = WalletIntentParams.parse(intent.params);
  const simulation = WalletSimulation.parse(intent.simulation);
  // The approval is for this exact transaction and nothing else.
  if (intentDigest({ walletAddress: wallet.address, params, simulation }) !== intent.approvedDigest) {
    throw new ValidationError('What would be signed no longer matches what was approved, so nothing was sent.');
  }
  if (!intent.approvedAt || now - Date.parse(intent.approvedAt) > APPROVAL_TTL_MS) {
    await walletsRepo.transitionIntent(id, 'APPROVED', 'EXPIRED', { error: 'The approval expired before it was sent. Simulate and approve again.' });
    throw new ValidationError('The approval expired before it was sent. Simulate and approve it again.');
  }
  const claimed = await walletsRepo.transitionIntent(id, 'APPROVED', 'SUBMITTING');
  if (!claimed) throw new ValidationError('That transaction is already being sent.');

  const a = requireAdapter();
  const sealed = await walletsRepo.sealedSecretOf(wallet.id);
  if (!sealed) {
    return (await walletsRepo.transitionIntent(id, 'SUBMITTING', 'FAILED', { error: 'The wallet is retired, so nothing was signed.' }))!;
  }
  const secret = new Uint8Array(Buffer.from(openSecret(sealed), 'base64'));
  let signed: { txHash: string; raw: string };
  try {
    signed = await a.sign(params.network, secret, params, simulation);
  } catch (error) {
    // Nothing was handed to the network, so this is a plain failure.
    const failed = await walletsRepo.transitionIntent(id, 'SUBMITTING', 'FAILED', { error: `It could not be signed: ${errorMessage(error)}` });
    await intentAudit(ownerId, failed!, 'wallet.intent.failed');
    return failed!;
  } finally {
    secret.fill(0);
  }
  await walletsRepo.transitionIntent(id, 'SUBMITTING', 'SUBMITTING', { txHash: signed.txHash });
  try {
    await a.broadcast(params.network, signed.raw);
  } catch (error) {
    // It may or may not have reached the network. Never sent again: checked by its hash.
    const unknown = await walletsRepo.transitionIntent(id, 'SUBMITTING', 'UNKNOWN', {
      error: `The network did not confirm it received this (${errorMessage(error)}). It is checked by its hash and never sent again.`,
    });
    await intentAudit(ownerId, unknown!, 'wallet.intent.unknown');
    return unknown!;
  }
  const submitted = await walletsRepo.transitionIntent(id, 'SUBMITTING', 'SUBMITTED', { error: null });
  await intentAudit(ownerId, submitted!, 'wallet.intent.submitted');
  return submitted!;
}

/** Reads the chain for a submitted or unknown transaction, by its hash. Never re-sends. */
export async function reconcileIntent(id: string, ownerId: string): Promise<WalletIntentRow> {
  const { intent } = await ownedIntent(id, ownerId);
  if (!['SUBMITTED', 'UNKNOWN', 'SUBMITTING'].includes(intent.status) || !intent.txHash) {
    throw new ValidationError('Only a sent transaction with a hash can be checked.');
  }
  const seen = await requireAdapter().receipt(intent.network as WalletNetwork, intent.txHash);
  if (seen === 'CONFIRMED' || seen === 'FAILED') {
    const next = await walletsRepo.transitionIntent(id, ['SUBMITTED', 'UNKNOWN', 'SUBMITTING'], seen, {
      error: seen === 'FAILED' ? 'The network included it and it failed.' : null,
    });
    if (next) await intentAudit(ownerId, next, `wallet.intent.${seen.toLowerCase()}`);
    return next ?? intent;
  }
  return intent;
}

export async function intentsOf(agentId: string, ownerId: string): Promise<WalletIntentRow[]> {
  await requireOwned(agentId, ownerId);
  return walletsRepo.listIntents(agentId);
}
